company_name: Simian, Inc
title: Continuous resilience testing for your application
timezone: UTC
url: https://www.simian-ci.com/
permalink: pretty
mailchimp:
  form-url: "//simian-ci.us15.list-manage.com/subscribe/post?u=b31cda805c99087d8948c2935&amp;id=da845f9db3"
footer:
  help:
  - text: Blog
    url:
  - text: Email
    url: mailto:support@simian-ci.com

gems:
  - jekyll-seo-tag
  - jekyll-autoprefixer

sass:
  style: compressed
  sass_dir: _sass

exclude: ['Gemfile', 'Gemfile.lock']
