company_name: Simian, Inc
title: Continuous resilience testing for your application
timezone: UTC
url: https://www.simian-ci.com/
permalink: pretty
mailchimp:
  form_url: "//simian-ci.us15.list-manage.com/subscribe/post?u=b31cda805c99087d8948c2935&amp;id=da845f9db3"
mail_to_link: mailto:support@simian-ci.com

gems:
  - jekyll-seo-tag
  - jekyll-autoprefixer

sass:
  sass_dir: _sass

exclude: [Gemfile, Gemfile.lock, README.md, gulpfile.js, package.json, node_modules]
